name: 'Ticketing Commands'
description: 'Slash commands for better GitHub Project management'
author: 'floholz'

# Add your action's branding here. This will appear on the GitHub Marketplace.
# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'command'
  color: 'yellow'

# Define your inputs here.
inputs:
  github_token:
    description: 'A GitHub personal access token with write access to the project.'
    required: true
  config_file:
    description: 'Config file path relative to your repo`s root.'
    required: false
    default: '.github/workflows/config/ticketing-cmd.yml'

# Define your outputs here.
outputs:
  command:
    description: 'Echo of the executed command'
  args:
    description: 'Echo of the executed command arguments'
  body:
    description: 'Echo of the passed command body (everything after the first line)'

runs:
  using: node20
  main: dist/index.js
