name: 'Project Slash Commands'
description: 'Slash commands for better GitHub Project management'
author: 'floholz'

# Add your action's branding here. This will appear on the GitHub Marketplace.
# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'command'
  color: 'yellow'

# Define your inputs here.
inputs:
  github_token:
    description: 'A GitHub personal access token with write access to the project.'
    required: true
  config_file:
    description: 'Config file path relative to your repo`s root.'
    required: false
    default: '.github/workflows/config/project-slash-cmd.yml'

# Define your outputs here.
outputs:
  project-v2-item-id:
    description: 'The Id of the created project V2 item.'

runs:
  using: node20
  main: dist/index.js
